/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * bb_uapi.h - ABI shared by the BlackBox kernel module and user-space tools.
 *
 * Every structure uses fixed-width types and explicit sizes so that the
 * kernel and the C++ programs agree on the layout.
 */
#ifndef BB_UAPI_H
#define BB_UAPI_H

#include <linux/types.h>
#include <linux/ioctl.h>

#define BB_DEVICE_NAME   "blackbox"
#define BB_DEVICE_PATH   "/dev/blackbox"
#define BB_MSG_MAX       104            /* bytes incl. terminating NUL */

/* Event levels (set with an optional "<N>" prefix on write) */
enum bb_level {
	BB_LVL_DEBUG = 0,
	BB_LVL_INFO  = 1,
	BB_LVL_WARN  = 2,
	BB_LVL_ERROR = 3,
};

/* Where an event came from */
enum bb_source {
	BB_SRC_USER      = 0,   /* written by a process through write() */
	BB_SRC_HEARTBEAT = 1,   /* generated by the kernel timer        */
	BB_SRC_DRIVER    = 2,   /* generated by the driver itself       */
};

/* One recorded event: exactly 128 bytes. */
struct bb_event {
	__u64 ts_ns;            /* wall-clock time, ns since the epoch  */
	__u64 seq;              /* monotonically increasing number      */
	__u32 pid;              /* PID of the writer (0 for kernel)     */
	__u8  level;            /* enum bb_level                        */
	__u8  source;           /* enum bb_source                       */
	__u16 len;              /* valid bytes in msg (without NUL)     */
	char  msg[BB_MSG_MAX];
};

/* Snapshot of the recorder state, returned by BB_IOC_GET_STATS. */
struct bb_stats {
	__u64 total_written;    /* events accepted since load/clear     */
	__u64 dropped_frozen;   /* writes rejected while frozen         */
	__u64 head_seq;         /* sequence number of the next event    */
	__u64 oldest_seq;       /* oldest event still in the buffer     */
	__u32 capacity;         /* ring size in events                  */
	__u32 used;             /* events currently stored              */
	__u32 frozen;           /* 1 if frozen                          */
	__u32 reserved;
};

#define BB_IOC_MAGIC       'B'
#define BB_IOC_FREEZE      _IO(BB_IOC_MAGIC, 1)   /* stop accepting writes   */
#define BB_IOC_UNFREEZE    _IO(BB_IOC_MAGIC, 2)   /* resume recording        */
#define BB_IOC_CLEAR       _IO(BB_IOC_MAGIC, 3)   /* discard stored events   */
#define BB_IOC_GET_STATS   _IOR(BB_IOC_MAGIC, 4, struct bb_stats)
#define BB_IOC_SEEK_OLDEST _IO(BB_IOC_MAGIC, 5)   /* move read cursor to oldest */

#endif /* BB_UAPI_H */
